FROM php:8.1.26

EXPOSE 8080

 COPY ./php.ini /usr/local/etc/php/conf.d/php.ini

RUN mkdir /var/log/php

RUN mkdir -p /var/www/html
WORKDIR /var/www/html

# Install Debian packagies
# PHP extension zip requires zlib1g-dev
# PHP extension imagick requires pkg-config, libmagickwand-dev
# WordPress Unit Test requires subversion subversion-tools
# RUN apt-get update \
#  && apt-get install -y \
#     git \
#     libmemcached-dev \
#     libmagickwand-dev \
#     libssl-dev \
#     libzip-dev \
#     default-mysql-client \
#     pkg-config \
#     unzip \
#     wget \
#     zip \
#     zlib1g-dev

# Debian provides zlib as zlib1g-dev.

RUN apt-get update \
 && apt-get install -y \
    libmemcached-dev \
    libssl-dev \
    zlib1g-dev
#    zip

# Install PHP extensions required by Wordpress
# RUN docker-php-ext-install \
#     exif \
#     intl \
#     mysqli \
#     zip \
#  && pecl install \
#     apcu \
#     igbinary \ 
#     imagick \
#     memcached \
#  && docker-php-ext-enable \
#     apcu \
#     igbinary \
#     imagick \
#     memcached

RUN pecl install memcached
RUN docker-php-ext-enable memcached

# Install WodrPress Core
# RUN wget -q https://ja.wordpress.org/latest-ja.zip -P /var/www/html
# RUN unzip -q /var/www/html/latest-ja.zip && rm -f /var/www/html/latest-ja.zip
# RUN mv -f /var/www/html/wordpress /var/www/html/wp 

# Install WP-CLI
# @see https://wp-cli.org/
# RUN wget -q https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -P /var/www/html \
# && chmod u+x /var/www/html/wp-cli.phar \
# && mv -f /var/www/html/wp-cli.phar /usr/local/bin/wp

# Copy wp-config.php
# COPY ./wp-config.php /var/www/html/wp/wp-config.php

# Set up mailhog
# RUN curl -sSLO https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 \
#     && chmod +x mhsendmail_linux_amd64 \
#     && mv mhsendmail_linux_amd64 /usr/local/bin/mhsendmail \
#     && echo 'sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025"' > /usr/local/etc/php/conf.d/sendmail.ini
# 
# RUN rm -rf /var/www/html/wp/wp-content
# RUN ln -s /var/www/html/wp-content /var/www/html/wp/wp-content

CMD ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html/wp"]
